backend:
  image: ghcr.io/eunhwa99/backend:latest
  imagePullSecrets: ghcr-secret
  envFromSecret: unsplash-secret
  service:
    type: ClusterIP
    port: 8000

frontend:
  image: ghcr.io/eunhwa99/frontend:latest
  imagePullSecrets: ghcr-secret
  service:
    type: ClusterIP
    port: 3000

ingress:
  enabled: true
  host: myapp.local
  paths:
    frontend: "/"
    backend: "/api"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
