image:
  repository: my-frontend
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  - name: REACT_APP_BACKEND_URL
    value: "http://backend-my-backend:8000" # Pod 내부 서비스 이름

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources:
  requests:
    cpu: "0"
    memory: "0"
  limits:
    cpu: "0"
    memory: "0"

autoscaling:
  enabled: false
